name: DBNet
base: ['config/ctw1500.yaml']
tag: LVC
arch:
  type: Model
  backbone:
    type: AcpNet
    pretrained: true
    model_name: CoAE_embed
    num_codes: 16
    in_channels: 3

  neck:
    type: Empty
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.55
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 3
trainer:
  seed: 2
  epochs: 1200
  log_iter: 10000
  show_images_iter: 50000
  resume_checkpoint: ''
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: true
dataset:
  train:
    dataset:
      args:
        data_path:
          - ./datasets/train_ctw1500.txt
        img_mode: RGB
    loader:
      batch_size: 8
      shuffle: true
      pin_memory: true
      num_workers: 6
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - ./datasets/test_ctw1500.txt
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 736
              resize_text_polys: true
          - type: MakeDividable
            args:
              divisor : 32
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: true
      pin_memory: false
      num_workers: 6
      collate_fn: ICDARCollectFN
